// Auto-generated by `supabase gen types typescript`. Do not edit by hand.
// Regenerate via the Supabase MCP `generate_typescript_types` whenever the
// schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      notifications: {
        Row: {
          body: string | null;
          created_at: string;
          id: string;
          link: string | null;
          read_at: string | null;
          title: string;
          type: string;
        };
        Insert: {
          body?: string | null;
          created_at?: string;
          id?: string;
          link?: string | null;
          read_at?: string | null;
          title: string;
          type: string;
        };
        Update: {
          body?: string | null;
          created_at?: string;
          id?: string;
          link?: string | null;
          read_at?: string | null;
          title?: string;
          type?: string;
        };
        Relationships: [];
      };
      parts: {
        Row: {
          category: string | null;
          created_at: string;
          current_quantity: number;
          id: string;
          location: string | null;
          name: string;
          notes: string | null;
          reorder_threshold: number | null;
          skaps_number: string;
          unit: string;
          updated_at: string;
        };
        Insert: {
          category?: string | null;
          created_at?: string;
          current_quantity?: number;
          id?: string;
          location?: string | null;
          name: string;
          notes?: string | null;
          reorder_threshold?: number | null;
          skaps_number: string;
          unit?: string;
          updated_at?: string;
        };
        Update: {
          category?: string | null;
          created_at?: string;
          current_quantity?: number;
          id?: string;
          location?: string | null;
          name?: string;
          notes?: string | null;
          reorder_threshold?: number | null;
          skaps_number?: string;
          unit?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          created_at: string;
          first_name: string | null;
          id: string;
          last_name: string | null;
        };
        Insert: {
          created_at?: string;
          first_name?: string | null;
          id: string;
          last_name?: string | null;
        };
        Update: {
          created_at?: string;
          first_name?: string | null;
          id?: string;
          last_name?: string | null;
        };
        Relationships: [];
      };
      submissions: {
        Row: {
          employee_name: string | null;
          external_row_id: string | null;
          form_type: string;
          id: string;
          line: string | null;
          machine_area: string | null;
          notes: string | null;
          part_description: string | null;
          pm_type: string | null;
          po_number: string | null;
          price: number | null;
          quantity: number | null;
          raw: Json;
          received_at: string | null;
          skaps_number: string | null;
          status: string;
          submitted_at: string;
          urgency: string | null;
        };
        Insert: {
          employee_name?: string | null;
          external_row_id?: string | null;
          form_type: string;
          id?: string;
          line?: string | null;
          machine_area?: string | null;
          notes?: string | null;
          part_description?: string | null;
          pm_type?: string | null;
          po_number?: string | null;
          price?: number | null;
          quantity?: number | null;
          raw: Json;
          received_at?: string | null;
          skaps_number?: string | null;
          status?: string;
          submitted_at: string;
          urgency?: string | null;
        };
        Update: {
          employee_name?: string | null;
          external_row_id?: string | null;
          form_type?: string;
          id?: string;
          line?: string | null;
          machine_area?: string | null;
          notes?: string | null;
          part_description?: string | null;
          pm_type?: string | null;
          po_number?: string | null;
          price?: number | null;
          quantity?: number | null;
          raw?: Json;
          received_at?: string | null;
          skaps_number?: string | null;
          status?: string;
          submitted_at?: string;
          urgency?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      public_inventory: {
        Row: {
          category: string | null;
          location: string | null;
          name: string | null;
          quantity_on_hand: number | null;
          reorder_threshold: number | null;
          skaps_number: string | null;
          unit: string | null;
          updated_at: string | null;
          used_last_30d: number | null;
        };
        Insert: {
          category?: string | null;
          location?: string | null;
          name?: string | null;
          quantity_on_hand?: never;
          reorder_threshold?: number | null;
          skaps_number?: string | null;
          unit?: string | null;
          updated_at?: string | null;
          used_last_30d?: never;
        };
        Update: {
          category?: string | null;
          location?: string | null;
          name?: string | null;
          quantity_on_hand?: never;
          reorder_threshold?: number | null;
          skaps_number?: string | null;
          unit?: string | null;
          updated_at?: string | null;
          used_last_30d?: never;
        };
        Relationships: [];
      };
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

export type Part = Database["public"]["Tables"]["parts"]["Row"];
export type PartInsert = Database["public"]["Tables"]["parts"]["Insert"];
export type PartUpdate = Database["public"]["Tables"]["parts"]["Update"];

export type Submission = Database["public"]["Tables"]["submissions"]["Row"];
export type SubmissionInsert = Database["public"]["Tables"]["submissions"]["Insert"];

export type Profile = Database["public"]["Tables"]["profiles"]["Row"];

export type Notification = Database["public"]["Tables"]["notifications"]["Row"];
export type NotificationInsert = Database["public"]["Tables"]["notifications"]["Insert"];

export type PublicInventoryRow = Database["public"]["Views"]["public_inventory"]["Row"];
